-
    subject_id: '0051275'
    unique_id: 'session_1'
    anat: '/data/Projects/ABIDE_Initiative/CPAC/RawData/UCLA_1/0051275/session_1/anat_1/mprage.nii.gz'
    rest: 
      rest_1_rest: '/data/Projects/ABIDE_Initiative/CPAC/RawData/UCLA_1/0051275/session_1/rest_1/rest.nii.gz'
    scan_parameters:
        tr: '3'
        acquisition: 'alt+z2'
        reference: '17'
        first_tr: '0'
        last_tr: 'None'
