anatomicalTemplate  :  /home2/data/Projects/ABIDE_Initiative/CPAC/RawData/%s/%s/session_1/*/mprage.nii.gz 

functionalTemplate  :  /home2/data/Projects/ABIDE_Initiative/CPAC/RawData/%s/%s/*/*/rest.nii.gz 

subjectList  :  /data/Projects/ABIDE_Initiative/CPAC/abide/config/test_one_subject/subject_list.txt 

exclusionSubjectList  :  None 

siteList  :  None 

scanParametersCSV  :  /data/Projects/ABIDE_Initiative/CPAC/abide/config/slice_timing_parameters.csv 

outputSubjectListLocation  :  /home2/data/Projects/ABIDE_Initiative/CPAC/abide/config/test_one_subject 

